# Generated by Django 4.2.21 on 2025-05-08 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Video",
                "verbose_name_plural": "Videolar",
            },
        ),
        migrations.AddField(
            model_name="video",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Açıklama"),
        ),
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Süre (saniye)"
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="thumbnails/",
                verbose_name="Küçük Resim",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Güncellenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(upload_to="videos/", verbose_name="Video Dosyası"),
        ),
        migrations.AlterField(
            model_name="video",
            name="metadata",
            field=models.JSONField(blank=True, null=True, verbose_name="Meta Veriler"),
        ),
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "İşlem Bekliyor"),
                    ("processing", "İşleniyor"),
                    ("ready", "Hazır"),
                    ("failed", "Hata Oluştu"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Başlık"),
        ),
        migrations.AlterField(
            model_name="video",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yüklenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
