# Generated by Django 4.2.21 on 2025-05-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "videos",
            "0002_alter_video_options_video_description_video_duration_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "İşlem Bekliyor"),
                    ("processing", "İşleniyor"),
                    ("ready", "Hazır"),
                    ("transcribed", "Transkript Edildi"),
                    ("failed", "Hata Oluştu"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
    ]
