# Generated by Django 4.2.21 on 2025-05-08 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("transcriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transcriptsegment",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Transkript Segmenti",
                "verbose_name_plural": "Transkript Segmentleri",
            },
        ),
        migrations.AddField(
            model_name="transcriptsegment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="transcriptsegment",
            name="end_time",
            field=models.FloatField(verbose_name="Bitiş Zamanı (saniye)"),
        ),
        migrations.AlterField(
            model_name="transcriptsegment",
            name="start_time",
            field=models.FloatField(verbose_name="Başlangıç Zamanı (saniye)"),
        ),
        migrations.AlterField(
            model_name="transcriptsegment",
            name="text",
            field=models.TextField(verbose_name="Metin"),
        ),
    ]
