# Generated by Django 4.2.21 on 2025-05-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userquizattempt",
            old_name="completed_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="userquizattempt",
            name="answers_json",
            field=models.TextField(blank=True, null=True),
        ),
    ]
